notifications:
  email: false

language: c
  
arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

install:
  - pip install --user numpy

script:
  - make aescpuid
  - ./aescpuid
  - make sshaes-demo-sw-encode sshaes-demo-hw-encode sshaes-demo-sw-decode sshaes-demo-hw-decode
  - make perf-geomean-aes.txt
  - echo "Speedup in geomean is:" && cat perf-geomean-aes.txt
